# docker-compose.service.yml
# Service Geliştirme ortamı

networks:
  sentiric-net: { name: "${NETWORK_NAME:-sentiric-net}", driver: bridge }

services:
  # --- AI SERVİSLERİ ---
  llm-service:
    build: { context: ../sentiric-llm-service }
    env_file: ["${ENV_FILE_PATH}"]
    ports: ["${LLM_SERVICE_PORT:-7860}:7860"]
    networks: [sentiric-net]
    restart: always
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 3m   